### ISSUE TITLE
Reference implementation doesn't conform to specification

### ISSUE THREAD

**Issue by bradrn** [catseye/ALPACA#10]
While contemplating #9, I realised that there is a case where the reference implementation doesn't conform to the specification. In particular:

> A representation declaration is not required for any given state.

So consider the following perfectly valid ALPACA definition, adapted from one of the examples:

```
neighbourhood Distant
  (<<< >>> ^^^ vvv);
state Space " "
  to Thing2 when 1 in Distant Thing;
state Thing "#";
state Thing2      /* Note the absence of representation declaration */
begin
#
```

Yet when I run this using the reference implementation:

```
-----
#
-----
Traceback (most recent call last):
  File "bin/alpaca", line 12, in <module>
    main.main(sys.argv)
  File "/mnt/c/Users/bradn/Documents/ALPACA/bin/../src/alpaca/main.py", line 197, in main
    output_frame(count, pf)
  File "/mnt/c/Users/bradn/Documents/ALPACA/bin/../src/alpaca/main.py", line 173, in output_frame
    rendered = str(pf)
  File "/mnt/c/Users/bradn/Documents/ALPACA/bin/../src/alpaca/playfield.py", line 106, in __str__
    return self.to_str(self.min_x, self.min_y, self.max_x, self.max_y)
  File "/mnt/c/Users/bradn/Documents/ALPACA/bin/../src/alpaca/playfield.py", line 99, in to_str
    s += self.represent(self.get(x, y))
TypeError: cannot concatenate 'str' and 'NoneType' objects
```

It works when I add a representation declaration to `Thing2`.

**Comment by bradrn** [comment]
After thinking about this issue a bit, I'm closing it. The problem in this case is that the reference implementation is trying to print something without a printable representation, causing it to throw an exception. Theoretically, the best way to solve this would be to add a command-line option for a default representation declaration, but that still feels a bit hacky, so I won't bother implementing it. (I'd be happy to implement it if anyone else wants it, though.)
